astro.config.mjs, package.json, pnpm-lock.yaml, src/layouts/BaseLayout.astro, src/layouts/Page.astro, src/lib/types/page.type.ts, src/pages/index.astro, src/styles/base.css, tailwind.config.cjs
Address #3
Please review on wether we should use tailwind and daisy ui or not.
=> Add tailwind and daisy UI

src/lib/components/Hero.svelte
change 2nd div class lg:bg-50% to lg:bg-100%
re-arrange text and elements inside hero with added span elements, add style at the bottom
=> add attribute data-hero into parent element

src/lib/components/Mission.svelte
=> #9 🚜 refactor: convert vanilla css to tailwind

src/lib/data/index.ts, src/lib/data/links.ts, src/routes/(landing)/+page.svelte, src/routes/(landing)/Header.svelte, src/routes/(landing)/Header.test.ts, tests/landing.test.ts
=> fix: #41 navbar link

src/lib/data/links.ts, src/routes/(landing)/+page.svelte, src/routes/(landing)/Header.svelte, src/routes/(landing)/Header.test.ts
=> fix : issue #40 and #41 

src/lib/components/CTA.svelte
=> Typographical error

src/lib/components/Mission.svelte
=> 🪄 style: Enhance Mission Component

src/lib/components/utils/ToggleTheme.svelte, src/routes/(landing)/Header.svelte
Need to create a new issue for the readability of navbar items.  should we solve it with font size change? I dont think so...
font weight? - likely solution
background for the navbar? - my recommendation @daedalus-developers/ui-ux  please check
=> #47 #48 Fix all navbar - related issues

package-lock.json, src/lib/components/CTA.svelte, src/lib/components/Mission.svelte, src/lib/components/Projects.svelte, src/lib/components/utils/CardsCourses.svelte, src/routes/(landing)/Footer.svelte, src/routes/(landing)/Header.svelte
- emphasized words with accent colors on CTA component (personally find it more impactful that way. combining craft with together makes more sense knowing our org's purpose)
- adjusted whitespace and centered some items from the footer
- improved readability on courses component
- transition on cards courses
- removed the blue border appearing from the input email box when focused
- fixed the blur overflow or smearing when scrolling from the navbar (just realized that another pr did this, but i personally find it better as well)
to
=> style: minor enhancement

src/app.css
=> Default Root CSS values

src/lib/components/events/Register.svelte, src/routes/(landing)/register/+page.svelte
This PR adds new functionality for the checkbox, radio, and file types in the eventRequirements factory.
The changes are as follows:
- Checkbox and radio will allow adding new choices into the fields.
- File contains a visible label to allow users to see the instructions.
These changes were used to build parts of the registration page.
=> #86 Jellyfish/registration page

src/lib/components/sections/hero.svelte, src/lib/components/sections/index.ts, src/routes/(default)/+page.svelte
feat: added responsive homepage
=> feat: issue #95 added hero section

src/lib/components/sections/hero.svelte, src/lib/components/sections/index.ts, src/routes/(default)/+page.svelte
* feat: issue#95 added homepage
* feat: exported Hero from hero.svelte
* refactor: changed the import as per the reviewer
=> feat: issue #95 added hero section (#105)

package.json, pnpm-lock.yaml, src/lib/components/layouts/default-layout.svelte, src/lib/components/sections/default-header.svelte, src/lib/components/utilities/Container.svelte, src/routes/(default)/+page.svelte, src/routes/(default)/DaedalusCommunity.svelte, src/routes/(default)/MissionVision.svelte, src/routes/(default)/Portfolio.svelte, src/routes/(default)/Team.svelte
implement design for index page
<Container /> component default class adjustment
create MissionVision component for index page
create DaedalusCommunity component for index page
create Portfolio component for index page
create Team component for index page
=> install embla carousel

pb/pb_migrations/1701930064_updated_projects.js, src/lib/components/index.ts, src/lib/components/projects/index.ts, src/lib/components/projects/project-card.svelte, src/lib/types/index.ts, src/lib/types/project.types.ts, src/routes/(default)/portfolio/+page.server.ts, src/routes/(default)/portfolio/+page.svelte
=> benok/issue97 Portfolio Page Implementation with Project Cards

src/lib/components/sections/hero.svelte
Closes #118 
handle different screen sizes
=> Hero Section responsiveness and add CTA button

src/routes/(default)/contact/+page.svelte
=> draft: Remove console.log statement and update

src/routes/(default)/contact/+page.svelte
=> fix issue #126

pb/pb_migrations/1702091077_updated_users_details.js, pb/pb_migrations/1702091152_updated_users_details.js, pb/pb_migrations/1702091247_updated_users_details.js, pb/pb_migrations/1702091315_updated_users_details.js, pb/pb_migrations/1702093073_updated_users_details.js, pb/pb_migrations/1702095555_updated_users_details.js, pb/pb_migrations/1702095585_updated_users_details.js, pb/pb_migrations/1702095600_updated_users_details.js, src/lib/components/forms/index.ts, src/lib/components/forms/link-input.svelte, src/lib/components/forms/user-form.svelte, src/lib/components/forms/userdetails-form.svelte, src/lib/types/user.types.ts, src/lib/utils/response.utils.ts, src/routes/(me)/+layout.svelte, src/routes/(me)/me/+page.server.ts, src/routes/(me)/me/+page.svelte, src/routes/api/actions/auth/+page.server.ts, src/routes/api/actions/users/+page.server.ts
Unimploemented RTE. issue to come.
=> feat: userdetails form

src/lib/components/forms/contact-form.svelte, src/lib/components/forms/email-input.svelte, src/lib/components/forms/index.ts, src/lib/components/forms/phone-input.svelte, src/lib/components/forms/text-input.svelte, src/lib/components/forms/textarea-input.svelte, src/lib/types/contact.types.ts, src/lib/types/index.ts, src/routes/(default)/contact/+page.server.ts, src/routes/(default)/contact/+page.svelte, src/routes/api/actions/contact/+page.server.ts
=> Contact Form Input Validation and connect to Server Action

src/app.html, src/app.postcss, src/lib/components/cards/team-card.svelte, src/lib/components/sections/FooterSubscribe.svelte, src/lib/components/sections/default-header.svelte, src/lib/components/sections/navbar.svelte, src/lib/server/getAllEvents.ts, src/lib/server/index.ts, src/lib/utils/index.ts, src/routes/(default)/+layout.server.ts, src/routes/(default)/+layout.svelte, src/routes/(default)/+page.server.ts, src/routes/(default)/+page.svelte, src/routes/(default)/Events.svelte, src/routes/(default)/MissionVision.svelte, src/routes/(default)/Projects.svelte, src/routes/(default)/Team.svelte, src/routes/(default)/events/+page.svelte, src/routes/+layout.svelte
Make home page components data dynamic and streamed
Navbar sticky
placeholders for homepage component for loading effect
=> Make home page components data dynamic and streamed

pb/pb_migrations/1702807878_updated_projects.js, pb/pb_migrations/1702811680_updated_events.js, src/lib/components/cards/project-card.svelte, src/lib/components/sections/default-footer.svelte, src/lib/components/utilities/Container.svelte, src/lib/server/queries/event.query.ts, src/lib/server/queries/index.ts, src/lib/server/queries/project.query.ts, src/lib/server/queries/team.query.ts, src/lib/server/queries/user.query.ts, src/lib/types/filter.types.ts, src/lib/utils/index.ts, src/routes/(default)/Events.svelte, src/routes/(default)/Projects.svelte, src/routes/(default)/events/+layout.svelte, src/routes/(default)/events/+page.server.ts, src/routes/(default)/events/+page.svelte, src/routes/(default)/events/[slug]/+page.server.ts, src/routes/(default)/events/[slug]/+page.svelte, src/routes/(default)/projects/+layout.svelte, src/routes/(default)/projects/+page.server.ts, src/routes/(default)/projects/+page.svelte, src/routes/(default)/projects/[slug]/+page.server.ts, src/routes/(default)/projects/[slug]/+page.svelte, src/routes/(default)/projects/tags/[tag]/+page.server.ts
Bugs found needs to address soon
Might be caused by the container element
=> feat: routing

src/lib/server/queries/event.query.ts, src/lib/utils/index.ts, src/routes/(default)/events/+page.server.ts, src/routes/(default)/events/+page.svelte, src/routes/(default)/events/event-paginator.svelte
=> feat: Event Pagination and filter Query

src/app.postcss, src/lib/components/forms/logout-button.svelte, src/lib/components/forms/user-form.svelte, src/lib/components/forms/userdetails-form.svelte, src/routes/(default)/events/[slug]/+page.svelte, src/routes/(default)/projects/[slug]/+page.svelte, src/routes/(profile)/+layout.server.ts, src/routes/(profile)/[username]/+page.server.ts, src/routes/(profile)/[username]/+page.svelte, src/routes/+layout.svelte, src/routes/api/actions/users/+page.server.ts, tests/test.ts
=> fix: /me forms

src/lib/components/sections/avatar-button.svelte, src/routes/(default)/events/[slug]/+page.svelte, src/routes/(default)/projects/[slug]/+page.svelte, src/routes/(profile)/[username]/+page.svelte, src/routes/api/actions/users/+page.server.ts
Closes #176 Error due to mismatch field in form action
=> fix: Fix linkedin icon #176

svelte.config.js
=> chore: set adapter to auoto

package.json, pnpm-lock.yaml, svelte.config.js
=> chore: add build:node
